INSERT INTO products (id, name, price, description, image_url, status) VALUES 
(11, 'Basil', 4.90, 'Basil, also called great basil, is a culinary herb of the family Lamiaceae. It is a tender plant, and is used in cuisines worldwide.', 'https://images.unsplash.com/photo-1527964105263-1ac6265a569f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80', 'Active'),
(12, 'Bay Leaves', 4.90, 'Bay leaves are pungent and have a sharp, bitter taste. As with many spices and flavourings, the fragrance of the bay leaf is more noticeable than its taste. When the leaf is dried, the aroma is herbal, slightly floral, and somewhat similar to oregano and thyme.', 'https://images.unsplash.com/photo-1498612753354-772a30629934?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80', 'Active'),
(13, 'Dill', 4.90, 'The dill plant (Anethum graveolens) provides feathery green leaves for the dill weed herb, while the flat, oval fruits make the dill seed spice. It is an annual herb related to celery that tends to replant itself and spread widely, which is good to know if you are considering planting it in your garden. Dill seeds are used in seasoning, such as in pickles.', 'https://images.unsplash.com/photo-1636154851820-c3cbc74d232d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80', 'Active'),
(14, 'Mint', 4.90, 'Mints are aromatic, almost exclusively perennial herbs. They have wide-spreading underground and overground stolons and erect, square, branched stems. The leaves are arranged in opposite pairs, from oblong to lanceolate, often downy, and with a serrated margin. Leaf colors range from dark green and gray-green to purple, blue, and sometimes pale yellow. The flowers are white to purple and produced in false whorls called verticillasters.', 'https://images.unsplash.com/photo-1603653856395-084002e5d39d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80', 'Active'),
(15, 'Oregano', 4.90, 'Oregano is a woody perennial plant, growing 20–80 cm tall, with opposite leaves 1–4 cm long. The flowers are purple, 3–4 mm long, produced in erect spikes in summer. It is sometimes called wild marjoram. Oregano is also an ornamental plant, with numerous cultivars bred for varying leaf colour, flower colour and habit.', 'https://images.pexels.com/photos/9476495/pexels-photo-9476495.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2', 'Active'),
(16, 'Parsley', 4.90, 'Garden parsley is a bright green, biennial plant in temperate climates. Where it grows as a biennial, in the first year, it forms a rosette of tripinnate leaves 10–25 cm long with numerous 1–3 cm leaflets, and a taproot used as a food store over the winter. In the second year, it grows a flowering stem to 75 cm (30 in) tall with sparser leaves and flat-topped 3–10 cm diameter umbels with numerous 2 mm diameter yellow to yellowish-green flowers. The seeds are ovoid, 2–3 mm long, with prominent style remnants at the apex.', 'https://images.unsplash.com/photo-1568493840567-5836c376e857?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80', 'Active'),
(17, 'Rosemary', 4.90, 'Salvia rosmarinus, commonly known as rosemary, is a shrub with fragrant, evergreen, needle-like leaves and white, pink, purple, or blue flowers, native to the Mediterranean region.', 'https://images.unsplash.com/photo-1519966124849-e51203b261ba?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80', 'Active'),
(18, 'Sage', 4.90, 'Sage is a perennial, evergreen subshrub, with woody stems, grayish leaves, and blue to purplish flowers. ', 'https://images.unsplash.com/photo-1584238944561-6a12da936b29?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80', 'Active'),
(19, 'Thyme', 4.90, 'Thyme is aromatic perennial evergreen herbs in the mint family Lamiaceae. Thymes are relatives of the oregano genus Origanum, with both plants being mostly indigenous to the Mediterranean region. Thymes have culinary, medicinal, and ornamental uses, and the species most commonly cultivated and used for culinary purposes is Thymus vulgaris. ', 'https://images.unsplash.com/photo-1589562037508-ae76f4c445e2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80', 'Active');